# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234b361fff36eeb79a1e9c872c766b08cc3990bdb9de744ee41eb8c5563f523fd5d051b7f74631316ce881bcc89b543f83c980f7537a4bd7b6377ae2b264ab02

test:
  secret_key_base: 0e058650947d4c2dd124d5959876af7e2d1aa464d5e7ad0883887c059452f618b6ec2a120384df3797203b70ea567ad57d0851badd975cab7c728b08913ba41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
